### ISSUE TITLE
GLIBC 2.33 Not Found

### ISSUE THREAD

**Issue by TheBicameralMind** [haystackeditor/haystack-editor#42]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.90.0
- OS Version: Ubuntu 20.04.6 LTS

Steps to Reproduce:

1. Download AppImage, e.g. to `haystack-editor-0.19.6.AppImage`
2. `chmod +x haystack-editor-0.19.6.AppImage`
3. `./haystack-editor-0.19.6.AppImage`; issue will occur on startup

Hey! First, very cool project. I've been looking for something like this for a while, especially for large established codebases. But when I try to run the AppImage `vscode-sqlite3.node` tries to load a version of GLIBC that I don't have. I imagine there's something weird going on with the packaging, since I can run "normal" VSCode v1.95.3 without issue. 

<details><summary>Log excerpt; this (or something like this) seems to output constantly</summary>
<p>

```
[main 2024-12-10T22:32:31.845Z] [uncaught exception in main]: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2024-12-10T22:32:31.845Z] Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at r (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:98)
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1637)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at Object.errorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9457)
    at u.triggerErrorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13859)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13610
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1654)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at h._loadModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9466)
    at h._resolve (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:7:452)
    at h.defineModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:5561)
    at h._relativeRequire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:6185)
    at e (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:8516)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32354
    at new Promise (<anonymous>)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32334
    at new Promise (<anonymous>)
    at A.p (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32314)
    at A.n (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:31866)
    at new A (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:29469)
    at k.t (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:84941)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83408
    at k.init (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83728)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:36555)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.z (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:757)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:976)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:29092)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:905)
    at ee.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:129171)
    at Q.rb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48765)
    at async Q.qb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48067)
    at async Q.Y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:34518)
    at async Q.open (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:30387)
    at async pt.startup (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:61825)
    at async Se.a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:113:1128)
[main 2024-12-10T22:32:31.845Z] [uncaught exception in main]: Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
[main 2024-12-10T22:32:31.845Z] Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at r (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:98)
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1637)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at Object.errorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9457)
    at u.triggerErrorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13859)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13610
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1654)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at h._loadModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9466)
    at h._resolve (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:7:452)
    at h.defineModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:5561)
    at h._relativeRequire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:6185)
    at e (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:8516)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32354
    at new Promise (<anonymous>)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32334
    at new Promise (<anonymous>)
    at A.p (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32314)
    at A.n (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:31866)
    at new A (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:29469)
    at k.t (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:84941)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83408
    at k.init (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83728)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:36555)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.z (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:757)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:976)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:29092)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:905)
    at ee.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:129171)
    at Q.rb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48765)
    at async Q.qb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48067)
    at async Q.Y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:34518)
    at async Q.open (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:30387)
    at async pt.startup (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:61825)
    at async Se.a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:113:1128)
[main 2024-12-10T22:32:37.841Z] Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar.unpacked/@vscode/sqlite3/build/Release/vscode-sqlite3.node)
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3-binding.js:4:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at v (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:647)
    at Object.<anonymous> (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/node_modules.asar/@vscode/sqlite3/lib/sqlite3.js:2:17)
    at a._compile (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1257)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at r (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:98)
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1637)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at Object.errorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9457)
    at u.triggerErrorback (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13859)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13610
    at n.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:5:1654)
    at u.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:4:13565)
    at a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9338)
    at h._loadModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:9466)
    at h._resolve (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:7:452)
    at h.defineModule (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:5561)
    at h._relativeRequire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:6185)
    at e (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/main.js:6:8516)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32354
    at new Promise (<anonymous>)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32334
    at new Promise (<anonymous>)
    at A.p (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:32314)
    at A.n (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:31866)
    at new A (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:44:29469)
    at k.t (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:84941)
    at /tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83408
    at k.init (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:108:83728)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:36555)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.z (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:757)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:976)
    at E.value (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:29092)
    at s.y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:682)
    at s.fire (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:37:905)
    at ee.load (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:110:129171)
    at Q.rb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48765)
    at async Q.qb (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:48067)
    at async Q.Y (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:34518)
    at async Q.open (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:30387)
    at async pt.startup (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:111:61825)
    at async Se.a (/tmp/.mount_haystaUUlnx8/usr/share/haystack-editor/resources/app/out/vs/code/electron-main/main.js:113:1128) {
  code: 'ERR_DLOPEN_FAILED',
  phase: 'loading',
  moduleId: '@vscode/sqlite3',
  neededBy: [ '===anonymous4===' ]
}

``` 
</p>
</details> 

My guess is it's similar to [this issue](https://github.com/posit-dev/positron/issues/3854), where the build environment is newer than mine -- but I'm not familiar with how this project is packaged.

**Comment by jay2142** [comment]
Thanks for reporting this! 
This is due to a mismatch between build environment & run environment, which unfortunately seems to be a fairly common issue w.r.t. packaging for Linux. We package on ubuntu 22.04, so the created executable expects a GLIBC version that is not present in 20.04.

Ideally we can switch to packaging on 20.04 to avoid this issue. I've attempted to set this up in the past but haven't succeeded just yet, due to an issue very similar to https://github.com/microsoft/vscode/issues/124467. I'll see if I can get this working.
