### ISSUE TITLE
Devcontainers don't work

### ISSUE THREAD

**Issue by BenBlumer** [haystackeditor/haystack-editor#8]
Does this issue occur when all extensions are disabled?: Yes (except Devcontainers)

- VS Code Version:  Haystack+Editor+Linux-0.18.zip
- OS Version:  Ubuntu 24.04.1 LTS

Steps to Reproduce:
1. Install Devcontainers extension if it isn't included by default.
1. Use a basic workspace / devcontainer interface (example attached: [basic_container.tar.gz](https://github.com/user-attachments/files/17168484/basic_container.tar.gz))
2.  File -> Open workspace from file -> dev.code-workspace
3. Either be prompted to "Reopen in container" or select from actions menu (ctrl+shift+p): Dev containers: open in container.
4. See Output:
```
[31 ms] Dev Containers 0.384.0 in VS Code 1.90.0 (cc102f3a62bd35f39ed059b99c5cce90e50a16e2).
[30 ms] Start: Resolving Remote
[72 ms] Setting up container for folder or workspace: /home/ben/basic_container/dev.code-workspace
[82 ms] Start: Check Docker is running
[82 ms] Start: Run: docker version
[143 ms] Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[150 ms] Start: Run: docker volume ls -q
[198 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/ben/basic_container --filter label=vsch.quality=stable
[243 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ben/basic_container --filter label=devcontainer.config_file=/home/ben/basic_container/.devcontainer/devcontainer.json
[290 ms] Start: Run: docker inspect --type container fce8304c3cef
[340 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/ben/basic_container
[387 ms] Start: Run: docker inspect --type container fce8304c3cef
[433 ms] Running Dev Containers CLI:   up --user-data-folder /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-someValue.sessionId_1727463801364 --workspace-folder /home/ben/basic_container --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ben/basic_container --id-label devcontainer.config_file=/home/ben/basic_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ben/basic_container/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[434 ms] Start: Run: /home/ben/Downloads/Haystack/haystack-editor /home/ben/.haystack-editor/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-someValue.sessionId_1727463801364 --workspace-folder /home/ben/basic_container --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/ben/basic_container --id-label devcontainer.config_file=/home/ben/basic_container/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/ben/basic_container/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --include-configuration --include-merged-configuration
[692 ms] @devcontainers/cli 0.69.0. Node.js v20.9.0. linux 6.8.0-45-generic x64.
[692 ms] Start: Run: docker buildx version
[796 ms] github.com/docker/buildx v0.17.1 257815a
[796 ms] 
[797 ms] Start: Run: docker -v
[842 ms] Start: Resolving Remote
[859 ms] Loading 146 extra certificates from /etc/ssl/certs/ca-certificates.crt.
[1032 ms] Start: Run: docker compose version --short
[1171 ms] Docker Compose version: 2.29.7
[1171 ms] Start: Run: docker compose -f /home/ben/basic_container/docker-compose.yml -f /home/ben/basic_container/.devcontainer/docker-compose.yml --profile * config
[1352 ms] name: basic_container
services:
  dev:
    build:
      context: /home/ben/basic_container
      dockerfile: dev.Dockerfile
    command:
      - /bin/sh
      - -c
      - while sleep 1000; do :; done
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/ben
        target: /workspaces
        bind:
          create_host_path: true
networks:
  default:
    name: basic_container_default
[1361 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=basic_container --filter label=com.docker.compose.service=dev
[1405 ms] Start: Run: docker inspect --type container fce8304c3cef
[1452 ms] Start: Run: docker events --format {{json .}} --filter event=start
[1460 ms] PersistedPath=/home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data, ContainerHasLabels=true
[1460 ms] Container was created with these config files: /home/ben/basic_container/docker-compose.yml,/home/ben/basic_container/.devcontainer/docker-compose.yml,/home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1727462928553.yml,/home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1727462932948-44e40c51-7811-449b-a3c1-625d09e4e139.yml
[1461 ms] Restoring /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1727462928553.yml from persisted storage
[1462 ms] Restoring /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1727462932948-44e40c51-7811-449b-a3c1-625d09e4e139.yml from persisted storage
[1463 ms] Start: Run: docker compose --project-name basic_container -f /home/ben/basic_container/docker-compose.yml -f /home/ben/basic_container/.devcontainer/docker-compose.yml -f /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1727462928553.yml -f /home/ben/.config/Haystack Editor/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.containerFeatures-1727462932948-44e40c51-7811-449b-a3c1-625d09e4e139.yml up -d --no-recreate
WARN[0000] /home/ben/basic_container/.devcontainer/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 1/1
 ✔ Container basic_container-dev-1  S...                                   0.4s 
[2030 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=basic_container --filter label=com.docker.compose.service=dev
[2074 ms] Start: Run: docker inspect --type container fce8304c3cef
[2119 ms] Start: Inspecting container
[2120 ms] Start: Run: docker inspect --type container fce8304c3cef1cad6b307dec6b6486c14ad1a7ddb4caf718873bd3b98896e44c
[2168 ms] Start: Run in container: /bin/sh
[2177 ms] Start: Run in container: uname -m
[2310 ms] x86_64
[2310 ms] 
[2310 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2313 ms] PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
[2313 ms] 
[2314 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2319 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[2321 ms] 
[2321 ms] 
[2321 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[2323 ms] 
[2323 ms] 
[2339 ms] Start: Run: docker inspect --type container fce8304c3cef1cad6b307dec6b6486c14ad1a7ddb4caf718873bd3b98896e44c
[2385 ms] Start: Run: docker exec -i -u root fce8304c3cef1cad6b307dec6b6486c14ad1a7ddb4caf718873bd3b98896e44c /bin/sh -c echo "New container started. Keep-alive process started." ; export VSCODE_REMOTE_CONTAINERS_SESSION=someValue.sessionId_1727463801364 ; /bin/sh
[2396 ms] Start: Inspecting container
[2396 ms] Start: Run: docker inspect --type container fce8304c3cef1cad6b307dec6b6486c14ad1a7ddb4caf718873bd3b98896e44c
[2445 ms] Start: Run in container: /bin/sh
[2456 ms] Start: Run in container: uname -m
[2522 ms] New container started. Keep-alive process started.
[2603 ms] x86_64
[2603 ms] 
[2604 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[2607 ms] PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
[2608 ms] 
[2609 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'root' || grep -E '^root|^[^:]*:[^:]*:root:' /etc/passwd || true)
[2614 ms] Start: Run: docker compose version --short
[2750 ms] Docker Compose version: 2.29.7
[2750 ms] Start: Setup shutdown monitor
[2752 ms] Forking shutdown monitor: /home/ben/.haystack-editor/extensions/ms-vscode-remote.remote-containers-0.384.0/dist/shutdown/shutdownMonitorProcess /run/user/1000/vscode-remote-containers-e549b8fe-93da-4fed-a23e-c661e786a8a4.sock dockerCompose Debug /home/ben/.config/Haystack Editor/logs/20240927T120224/window1/exthost/ms-vscode-remote.remote-containers 1727463801291
[2767 ms] Start: Run in container: test -d '/root/.haystack-server'
[2769 ms] 
[2770 ms] 
[2770 ms] Start: Run in container: test ! -f '/root/.haystack-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/root/.haystack-server/data/Machine' && { > '/root/.haystack-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2774 ms] 
[2774 ms] 
[2774 ms] Exit code 1
[2775 ms] Start: Run in container: cat /root/.haystack-server/data/Machine/settings.json
[2778 ms] 
[2779 ms] cat: /root/.haystack-server/data/Machine/settings.json: No such file or directory
[2779 ms] Exit code 1
[2779 ms] Start: Run in container: test -d '/root/.haystack-server/bin/cc102f3a62bd35f39ed059b99c5cce90e50a16e2'
[2781 ms] 
[2781 ms] 
[2782 ms] Exit code 1
[2782 ms] Start: Run in container: test -d '/vscode/haystack-server/bin/linux-x64/cc102f3a62bd35f39ed059b99c5cce90e50a16e2'
[2784 ms] 
[2784 ms] 
[2785 ms] Exit code 1
[2786 ms] Installing VS Code Server for commit cc102f3a62bd35f39ed059b99c5cce90e50a16e2
[2787 ms] Start: Downloading VS Code Server
[2787 ms] cc102f3a62bd35f39ed059b99c5cce90e50a16e2 linux-x64 stable
[3135 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:cc102f3a62bd35f39ed059b99c5cce90e50a16e2/server-linux-x64/stable): HTTP 404 - Not Found
[3136 ms] Retrying to download VS Code Server.
[3269 ms] Error: Server returned 404
    at a (vscode-file://vscode-app/home/ben/Downloads/Haystack/resources/app/out/vs/workbench/workbench.desktop.main.js:693:43685)
    at k.download (vscode-file://vscode-app/home/ben/Downloads/Haystack/resources/app/out/vs/workbench/workbench.desktop.main.js:694:1768)

```

**Comment by SurpassHR** [comment]
same issue
```bash
[7 ms] Dev Containers 0.384.0 in VS Code 1.90.0 (cc102f3a62bd35f39ed059b99c5cce90e50a16e2).
[7 ms] Start: Resolving Remote
[8 ms] Setting up container: /compassionate_thompson
[10 ms] Start: Run: wsl -d Ubuntu-20.04 -e wslpath -u \\wsl.localhost\Ubuntu-20.04\
[204 ms] Start: Run: wsl -d Ubuntu-20.04 -e /bin/sh -c cd '/' && /bin/sh
[211 ms] Start: Run in host: id -un
[299 ms] h30045134
[299 ms] 
[299 ms] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'h30045134' || grep -E '^h30045134|^[^:]*:[^:]*:h30045134:' /etc/passwd || true)
[301 ms] Start: Run in host: echo ~
[301 ms] /home/h30045134
[301 ms] 
[302 ms] Start: Run in host: test -f '/home/h30045134/.haystack-server/cli/servers/Stable-cc102f3a62bd35f39ed059b99c5cce90e50a16e2/server/node'
[303 ms] 
[303 ms] 
[303 ms] Exit code 1
[303 ms] Start: Run in host: test -f '/home/h30045134/.haystack-editor/cli/servers/Stable-cc102f3a62bd35f39ed059b99c5cce90e50a16e2/server/node'
[304 ms] 
[304 ms] 
[304 ms] Exit code 1
[304 ms] Start: Run in host: test -f '/home/h30045134/.haystack-server/bin/cc102f3a62bd35f39ed059b99c5cce90e50a16e2/node'
[305 ms] 
[305 ms] 
[305 ms] Start: Run in host: test -f '/home/h30045134/.haystack-server/bin/cc102f3a62bd35f39ed059b99c5cce90e50a16e2/node_modules/node-pty/package.json'
[305 ms] 
[306 ms] 
[306 ms] Start: Run in host: test -f '/home/h30045134/.vscode-remote-containers/dist/vscode-remote-containers-server-0.384.0.js'
[306 ms] 
[307 ms] 
[309 ms] userEnvProbe: loginInteractiveShell (default)
[310 ms] userEnvProbe: not found in cache
[310 ms] userEnvProbe shell: /bin/bash
[713 ms] userEnvProbe PATHs:
Probe:     '/usr/local/java/jdk1.8.0_242/bin:/opt/python/bin:/home/h30045134/.wsl-auto-setup/bin:/mnt/c/WINDOWS:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS/System32/Wbem:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/Windows:/mnt/c/Windows/system32:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/e/Program Files/WeCode/ide/bin:/mnt/e/DevEnv/mingw64/bin:/mnt/e/Program Files/MacType:/mnt/e/Program Files/VSCode-huawei/bin:/mnt/e/Program Files/Microsoft VS Code Insiders/bin:/mnt/e/Program Files/Microsoft VS Code/bin:/mnt/e/DevEnv/nodejs/:/mnt/c/ProgramData/chocolatey/bin:/mnt/e/Program Files/Bandizip/:/mnt/e/Program Files/Git/cmd:/mnt/e/DevEnv/mingw64/x86_64-w64-mingw32/include:/mnt/e/DevEnv/Cygwin/bin:/mnt/e/DevEnv/CLibs/SFML-2.6.1/bin:/mnt/e/DevEnv/CLibs/SFML-2.6.1/bin:/mnt/e/DevEnv/CLibs/SFML-2.6.1/include/SFML:/mnt/e/DevEnv/CLibs/SFML-2.6.1/include/SFML:/mnt/e/DevEnv/mingw64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++:/mnt/e/DevEnv/miniconda3:/mnt/e/DevEnv/miniconda3/Library/mingw-w64/bin:/mnt/e/DevEnv/miniconda3/Library/usr/bin:/mnt/e/DevEnv/miniconda3/Library/bin:/mnt/e/DevEnv/miniconda3/Scripts:/mnt/c/Users/h30045134/.cargo/bin:/mnt/e/DevEnv/Python/Python38/Scripts/:/mnt/e/DevEnv/Python/Python38/:/mnt/c/Users/h30045134/AppData/Local/Microsoft/WindowsApps:/mnt/e/Program Files/Sublime Text:/mnt/e/DevEnv/CMake/bin:/mnt/e/DevEnv/jdk8/bin:/mnt/e/Program Files/JetBrains/CLion 2023.1.3/bin:/mnt/e/DevEnv/Python/Python37/Scripts/:/mnt/e/DevEnv/Python/Python37/:/mnt/c/Users/h30045134/AppData/Roaming/npm:/mnt/e/Program Files/Hyper/resources/bin:/mnt/c/Users/h30045134/AppData/Local/JetBrains/Toolbox/scripts:/mnt/c/Users/h30045134/AppData/Local/Microsoft/WindowsApps:/mnt/e/DevEnv/mingw64/x86_64-w64-mingw32/include:/mnt/e/DevEnv/mingw64/include:/mnt/e/DevEnv/mingw64/bin:/snap/bin'
Container: None
[716 ms] Start: Run in Host: docker inspect --type container /compassionate_thompson
[757 ms] Start: Check Docker is running
[757 ms] Start: Run in Host: docker version
[775 ms] Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.1
 Git commit:        24.0.7-0ubuntu2~20.04.1
 Built:             Wed Mar 13 20:29:24 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
[775 ms]  Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.1
  Git commit:       24.0.7-0ubuntu2~20.04.1
  Built:            Wed Mar 13 20:29:24 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
[778 ms] Running Dev Containers CLI:   set-up --container-id c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de --container-session-data-folder /tmp/devcontainers-someValue.sessionId_1727496706391 --log-level debug --log-format json --default-user-env-probe loginInteractiveShell --skip-post-create --include-configuration --include-merged-configuration
[778 ms] Start: Checking for Dev Containers CLI
[788 ms] Start: Run in Host: /home/h30045134/.haystack-server/bin/cc102f3a62bd35f39ed059b99c5cce90e50a16e2/node /home/h30045134/.vscode-remote-containers/dist/dev-containers-cli-0.384.0/dist/spec-node/devContainersSpecCLI.js set-up --container-id c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de --container-session-data-folder /tmp/devcontainers-someValue.sessionId_1727496706391 --log-level debug --log-format json --default-user-env-probe loginInteractiveShell --skip-post-create --include-configuration --include-merged-configuration
[949 ms] @devcontainers/cli 0.69.0. Node.js v16.20.2. linux 5.15.153.1-microsoft-standard-WSL2 x64.
[949 ms] Start: Run: docker buildx version
[969 ms] 
[969 ms] docker: 'buildx' is not a docker command.
See 'docker --help'

[969 ms] Exit code 1
[969 ms] Start: Run: docker -v
[985 ms] Start: Run: docker inspect --type container c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de
[1003 ms] Start: Inspecting container
[1003 ms] Start: Run: docker inspect --type container c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de
[1024 ms] Start: Run in container: /bin/sh
[1030 ms] Start: Run in container: uname -m
[1062 ms] x86_64
[1062 ms] 
[1062 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1064 ms] NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[1064 ms] 
[1064 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'slave1' || grep -E '^slave1|^[^:]*:[^:]*:slave1:' /etc/passwd || true)
[1067 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcEnvironmentMarker'
[1068 ms] 
[1068 ms] 
[1068 ms] Start: Run in container: test -f '/var/devcontainer/.patchEtcProfileMarker'
[1070 ms] 
[1070 ms] 
[1075 ms] Start: Inspecting container
[1075 ms] Start: Run in Host: docker inspect --type container c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de
[1099 ms] Start: Run in Host: docker exec -i -u slave1 -e VSCODE_REMOTE_CONTAINERS_SESSION=someValue.sessionId_1727496706391 c5712a98b085d39c3885de0bd4e1104664acc6135befcd8e64e50a8043c634de /bin/sh
[1104 ms] Start: Run in container: uname -m
[1133 ms] x86_64
[1133 ms] 
[1133 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[1135 ms] NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
[1135 ms] 
[1135 ms] Start: Run in container:  (command -v getent >/dev/null 2>&1 && getent passwd 'slave1' || grep -E '^slave1|^[^:]*:[^:]*:slave1:' /etc/passwd || true)
[1138 ms] Start: Run in container: test -d '/home/slave1/.haystack-server'
[1139 ms] 
[1139 ms] 
[1139 ms] Start: Run in container: test ! -f '/home/slave1/.haystack-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/slave1/.haystack-server/data/Machine' && { > '/home/slave1/.haystack-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[1141 ms] 
[1141 ms] 
[1141 ms] Exit code 1
[1141 ms] Start: Run in container: cat /home/slave1/.haystack-server/data/Machine/settings.json
[1143 ms] 
[1143 ms] cat: /home/slave1/.haystack-server/data/Machine/settings.json: No such file or directory
[1143 ms] Exit code 1
[1144 ms] Start: Run in container: test -d '/home/slave1/.haystack-server/bin/cc102f3a62bd35f39ed059b99c5cce90e50a16e2'
[1145 ms] 
[1145 ms] 
[1145 ms] Exit code 1
[1146 ms] Installing VS Code Server for commit cc102f3a62bd35f39ed059b99c5cce90e50a16e2
[1146 ms] Start: Downloading VS Code Server
[1146 ms] cc102f3a62bd35f39ed059b99c5cce90e50a16e2 linux-x64 stable
[1750 ms] Failed to download VS Code Server (https://update.code.visualstudio.com/commit:cc102f3a62bd35f39ed059b99c5cce90e50a16e2/server-linux-x64/stable): HTTP 404 - Not Found
[1750 ms] Retrying to download VS Code Server.
[1872 ms] Error: Server returned 404
    at a (vscode-file://vscode-app/e:/Program%20Files/Haystack%20Editor/resources/app/out/vs/workbench/workbench.desktop.main.js:693:43685)
    at k.download (vscode-file://vscode-app/e:/Program%20Files/Haystack%20Editor/resources/app/out/vs/workbench/workbench.desktop.main.js:694:1768)
```

```bash
2024-09-28 12:11:45.544 [info] Extension host with pid 56200 started
2024-09-28 12:11:45.544 [info] [resolveAuthority(attached-container,1)][0ms] activating remote resolvers attached-container+7b22636f6e7461696e65724e616d65223a222f636f6d70617373696f6e6174655f74686f6d70736f6e222c22637764223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32302e30345c5c227d
2024-09-28 12:11:45.544 [info] [resolveAuthority(attached-container,1)][0ms] activating resolver for attached-container+7b22636f6e7461696e65724e616d65223a222f636f6d70617373696f6e6174655f74686f6d70736f6e222c22637764223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32302e30345c5c227d...
2024-09-28 12:11:45.546 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-containers, startup: false, activationEvent: 'onResolveRemoteAuthority:attached-container'
2024-09-28 12:11:45.664 [info] [resolveAuthority(attached-container,1)][123ms] invoking final resolve()...
2024-09-28 12:11:46.678 [info] [resolveAuthority(attached-container,1)][1137ms] waiting...
2024-09-28 12:11:47.528 [error] Error: Server returned 404
    at a (vscode-file://vscode-app/e:/Program%20Files/Haystack%20Editor/resources/app/out/vs/workbench/workbench.desktop.main.js:693:43685)
    at k.download (vscode-file://vscode-app/e:/Program%20Files/Haystack%20Editor/resources/app/out/vs/workbench/workbench.desktop.main.js:694:1768) _workbench.downloadResource undefined
2024-09-28 12:11:47.679 [info] [resolveAuthority(attached-container,1)][2138ms] waiting...
2024-09-28 12:11:48.689 [info] [resolveAuthority(attached-container,1)][3148ms] waiting...
2024-09-28 12:11:49.692 [info] [resolveAuthority(attached-container,1)][4151ms] waiting...
2024-09-28 12:11:50.239 [error] [resolveAuthority(attached-container,1)][4697ms] returned an error An unknown error occurred. Please consult the log for more details.
2024-09-28 12:11:50.288 [info] Eager extensions activated
2024-09-28 12:11:50.318 [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl, startup: false, activationEvent: 'onStartupFinished'
```

**Comment by AkshaySG14** [comment]
Hi sorry about this! We need to do some backend work on our end to fix this, but we're aware of the issue!
